### PR TITLE
also escape + char on regex, its not forbidden

### LINKED ISSUE #1066: Proper handling of regular expressions for states
The current implementation of pattern replacement doesn't work:
```js
pattern = pattern
    .replace(/\?/g, '\\?')
    .replace(/\./g, '\\.')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)')
    .replace(/\[/g, '\\[')
    .replace(/]/g, '\\]')
    .replace(/\*/g, '.*');
```

Please replace it with one that also supports `+`, doesn't handle excluded characters (see below) and is faster:
```js
pattern = pattern
    .replace(/[-\/^$+.()|{}]/g, '\\$&')
    .replace(/\*/g, '.*');
```

Excluded characters are according to the code:
```js
FORBIDDEN_CHARS   = /[\][*,;'"`<>\\?]/g;
```

**Suggestion:** we could also support `?` as a single character "wildcard" similar to Windows:
```js
pattern = pattern
    .replace(/[-\/^$+.()|{}]/g, '\\$&')
    .replace(/\*/g, '.*')
    .replace(/\?/g, '.');
```

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1066
- and support `?` as single char wild card, like it's done by redis

### CODE REVIEW

File: lib/tools.js [hunk 1]
```diff
@@ -1702,32 +1702,16 @@ function setQualityForInstance(objects, states, namespace, q) {
...
-        .replace(/\?/g, '\\?')
-        .replace(/\./g, '\\.')
-        .replace(/\(/g, '\\(')
-        .replace(/\)/g, '\\)')
-        .replace(/\[/g, '\\[')
-        .replace(/]/g, '\\]')
-        .replace(/\*/g, '.*');
+    pattern = pattern.replace(/[-/\\^$+?.()|[\]{}]/g, '\\$&')
+        .replace(/\*/g, '.*')
+        .replace(/\?/g, '.'); // supporting ? as single char wild card like redis does
```
Comment (AlCalzone) [inline lib/tools.js:1712]: I think you need to remove the question mark from line 1710 if you replace it here.

Comment (foxriver76) [reply lib/tools.js:1712]: yes, of course ;-)

**Comment by foxriver76** [comment]
after some investigation -> single char wildcards won't work out of the box for getObjectView/List because of the starkey/endkey logic, which is also sometimes used internally e.g. for `getForeignStates`

**Comment by AlCalzone** [comment]
I would be fine with no single char wildcard.

**Comment by GermanBluefox** [comment]
> I would be fine with no single char wildcard.

I too

**Comment by Apollon77** [comment]
@foxriver76 what we should to docs and where?
