### PR TITLE
Ensure what you've backuped is what you get on restore

### LINKED ISSUE #1595: Wrong version of admin after restore from backup
If I install a fresh version of js-controller(v3.x)+admin(v5)+discovery(?), 
after the backup recovery with old objects with admin@v4, 
the adapter tab in admin shows, that admin has v5, but all `system.adapter.admin.x` objects have version 4 
and the conditions checking during the installation of other adapters, that depends on admin@v5 failed.

Favorite solution after discussion:
* The restore process should uninstall the adapters that are on the system (in general, or if version mismatch to the version in the backup). The next controller start will make sure that the corect versions are installed automatically
* For js-controller  version (that should also mismatch) the idea is to check the version from backup and if it mismatches then stop the restore process and tell the user to install the correct js-controller version (as required n backup). We should offer a "--force-controller-mismatch" (name not final! maybe only --force) flag for restore to ignore this and accept the newer js-controller and update the objects accordingly and run an "setup first" after restore

### PR DESCRIPTION
**Pull request by foxriver76**
closes #1595 

- we now remove all current installed adapters before restoring the backup
- we check the controller version, if it differs we do not restore
- if user stills wants to restore with current version, `force` flag has been introduced

### CODE REVIEW

File: packages/controller/lib/setup/setupBackup.js [hunk 1]
```diff
@@ -670,6 +679,52 @@ class BackupRestore {
...
+
+            try {
+                const ioPackJson = fs.readJsonSync(path.join(controllerDir, 'io-package.json'));
+                const backupJson = JSON.parse(data);
+                const hostObj = backupJson.objects.find(obj => obj.id === `system.host.${backupHostname}`);
+                if (hostObj.value.common.installedVersion !== ioPackJson.common.version) {
+                    console.warn('The current version of js-controller differs from the version in the backup.');
+                    console.warn('The js-controller version of the backup can not be restored automatically.');
+                    console.warn(
+                        `To restore the js-controller version of the backup, execute npm i iobroker.js-controller@${hostObj.value.common.installedVersion} --production inside your ioBroker directory`
```
Comment (Apollon77) [inline packages/controller/lib/setup/setupBackup.js:696]:
```suggestion
                        `To restore the js-controller version of the backup, execute "npm i iobroker.js-controller@${hostObj.value.common.installedVersion} --production" inside your ioBroker directory`
```

File: packages/controller/lib/setup/setupBackup.js [hunk 2]
```diff
@@ -670,6 +679,52 @@ class BackupRestore {
...
+
+                    return EXIT_CODES.CANNOT_RESTORE_BACKUP;
+                }
+            } catch {
+                // ignore
+            }
+        }
+
+        const nodeModulePath = path.join(controllerDir, '..');
+        const nodeModuleDirs = fs.readdirSync(nodeModulePath);
```
Comment (Apollon77) [inline packages/controller/lib/setup/setupBackup.js:710]: better use fileObjs = fs.readdirSync(__dirname, { withFileTypes: true }); ?! then you can really only check the directories and not get unintentially files too

File: packages/controller/lib/setup/setupBackup.js [hunk 3]
```diff
@@ -697,9 +752,21 @@ class BackupRestore {
         await this._reloadAdapterObject(packageIO ? packageIO.objects : null);
         // copy all files into iob-data
         await this._copyBackupedFiles(pathLib.join(tmpDir, 'backup'));
+
+        if (force) {
+            // js-controller version has changed (setup never called for this version)
+            console.log('Forced restore - executing setup ...');
+            const cpPromise = require('promisify-child-process');
+            await cpPromise.exec(
```
Comment (Apollon77) [inline packages/controller/lib/setup/setupBackup.js:760]: try/catch? Feels needed

File: packages/controller/lib/setup/setupBackup.js [hunk 4]
```diff
@@ -670,6 +679,52 @@ class BackupRestore {
...
+            if (
+                dirName.startsWith(`${tools.appName.toLowerCase()}.`) &&
+                dirName !== `${tools.appName.toLowerCase()}.js-controller`
+            ) {
+                try {
+                    const packJson = fs.readJsonSync(path.join(nodeModulePath, dirName, 'package.json'));
+                    console.log(`Removing current installation of ${packJson.name}`);
+                    await tools.uninstallNodeModule(packJson.name);
+                } catch {
+                    // ignore
```
Comment (Apollon77) [inline packages/controller/lib/setup/setupBackup.js:723]: I would log a line "could not delete ... bla ... please executa "iob upload name"

**Review by Apollon77 — CHANGES_REQUESTED** [review]

File: packages/controller/lib/setup/setupBackup.js (hunk 4 above)
Comment (foxriver76) [reply packages/controller/lib/setup/setupBackup.js:723]: all adapters will be uploaded later anyways

Comment (foxriver76) [reply packages/controller/lib/setup/setupBackup.js:723]: https://github.com/ioBroker/ioBroker.js-controller/blob/506b23dd40a5402f57846faa3e79b07659d09398/packages/controller/lib/setup/setupBackup.js#L596

Comment (Apollon77) [reply packages/controller/lib/setup/setupBackup.js]: ahh ok ... hm ... but why this was then not happening before? In fact the missing eta data ala upload is one of the reasons for this topic
