### PR TITLE
optimize some types and trim read docker version string

### LINKED ISSUE #2374: @iobroker/types has wrong types for adapter.setTimeout etc
While updating my typescript adapters to @iobroker/adapter-core 3.x I noticed that the types from @iobroker/types seams to be incorrect for timeout and interval related functions.

* `adapter.setTimeout(...)` returns `NodeJS.Timeout` but should be `ioBroker.Timeout`
* `adapter.setInterval(...)` returns `NodeJS.Timeout` but should be `ioBroker.Interval`
* `adapter.clearTimeout(timer)` takes `NodeJS.Timeout` but should take `ioBroker.Timeout`
* `adapter.clearInterval(interval)` takes `NodeJS.Timeout` but should take `ioBroker.Interval`

This leads to type check errors like [this one](https://github.com/crycode-de/ioBroker.ds18b20/actions/runs/5721886482/job/15504130540?pr=111#step:2:454).

### PR DESCRIPTION
**Pull request by foxriver76**
closes #2374

### CODE REVIEW

**Review by Apollon77 — APPROVED** [review]

File: packages/adapter/src/lib/adapter/adapter.ts [hunk 1]
```diff
@@ -2503,7 +2503,7 @@ export class AdapterClass extends EventEmitter {
      * @param args - as many arguments as needed, which will be passed to setTimeout
      * @returns timer id
      */
-    setTimeout(cb: unknown, timeout: unknown, ...args: unknown[]): NodeJS.Timeout | void {
+    setTimeout(cb: unknown, timeout: unknown, ...args: unknown[]): ioBroker.Timeout | void {
```
Comment (AlCalzone) [inline packages/adapter/src/lib/adapter/adapter.ts:2506]:
```suggestion
    setTimeout(cb: unknown, timeout: unknown, ...args: unknown[]): ioBroker.Timeout | undefined {
```

The typical meaning of `void` is "this might return something, but you shouldn't use it".

File: packages/adapter/src/lib/adapter/adapter.ts [hunk 2]
```diff
@@ -2492,7 +2492,7 @@ export class AdapterClass extends EventEmitter {
     }
 
     // external signature
-    setTimeout(cb: TimeoutCallback, timeout: number, ...args: any[]): NodeJS.Timeout | void;
+    setTimeout(cb: TimeoutCallback, timeout: number, ...args: any[]): ioBroker.Timeout;
```
Comment (AlCalzone) [inline packages/adapter/src/lib/adapter/adapter.ts:2495]:
```suggestion
    setTimeout(cb: TimeoutCallback, timeout: number, ...args: any[]): ioBroker.Timeout | undefined;
```
right? The internal signature can return `undefined`.

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: packages/adapter/src/lib/adapter/adapter.ts (hunk 2 above)
Comment (foxriver76) [reply packages/adapter/src/lib/adapter/adapter.ts:2495]: Yes we can do so but then we should also allow undefined be passed to clear methods else it will be unhandy again.

File: packages/adapter/src/lib/adapter/adapter.ts [hunk 3]
```diff
@@ -2542,8 +2542,8 @@ export class AdapterClass extends EventEmitter {
      */
     clearTimeout(timer: unknown): void {
         // should we validate this?
-        clearTimeout(timer as any);
-        this._timers.delete(timer as any);
+        clearTimeout(timer as NodeJS.Timeout);
```
Comment (AlCalzone) [inline packages/adapter/src/lib/adapter/adapter.ts:2545]: I'd add
```ts
if (timer == undefined) return;
```
as the first line

File: packages/adapter/src/lib/adapter/adapter.ts [hunk 4]
```diff
@@ -2620,8 +2620,8 @@ export class AdapterClass extends EventEmitter {
      */
     clearInterval(interval: unknown): void {
         // should we validate it is a valid interval?
-        clearInterval(interval as any);
-        this._intervals.delete(interval as any);
+        clearInterval(interval as NodeJS.Timeout);
```
Comment (AlCalzone) [inline packages/adapter/src/lib/adapter/adapter.ts:2623]: dito

**Review by AlCalzone — CHANGES_REQUESTED** [review]
Maybe I'm being paranoid, but we should avoid accidentally using an undefined timer

**Review by AlCalzone — APPROVED** [review]
