### PR TITLE
fixes for file commands

### LINKED ISSUE #589: writeFile does not correctly sanitize Windows path separators, `iob rm` hangs indefinitely
I accidentally wrote a file using `adapter.writeFile` that had a Windows path separator `\` instead of `/`. This lands as-is in the files DB:
```
$ ./iob.bat list files zwave2.0

C:\iobroker>node node_modules/iobroker.js-controller/iobroker.js list files zwave2.0

-- zwave2.0 --
   Modified at  |Permission|     User     |     Group    | Size | Name
----------------+----------+--------------+--------------+------+---------
                 d?????????                                      zwave2.0/cache/
2020-01-04 13:48 -rw-r--r--          admin  administrator   1834 zwave2.0/cache\f6bda625.json
```

Furthermore, the `rm` command hangs indefinitely
```
$ ./iob.bat rm "zwave2.0/cache\\f6bda625.json"

C:\iobroker>node node_modules/iobroker.js-controller/iobroker.js rm zwave2.0/cache\f6bda625.json
[ nothing happens here]
```

### PR DESCRIPTION
**Pull request by foxriver76**
- always repalce backslashes for unix paths
- also do this in normalize to fix old files
- fixes #589
- cache meta objects and only allow writing files to objects of type meta (for now, we only deprecate)

### CODE REVIEW

**Comment by Apollon77** [comment]
hehe windows tests don'tlike the change :-) interesting that it only affects windows

**Comment by Apollon77** [comment]
aahhh ... or it is because ijects lib is not yet adjusted ... we should add that and update version of objects lib here to prove that. WIll update objects lib later

File: lib/objects/objectsInMemFileDB.js [hunk 1]
```diff
@@ -98,6 +101,27 @@ class ObjectsInMemoryFileDB extends InMemoryFileDB {
...
+     *
+     * @param {string} id to check
+     * @throws Error if id is invalid
+     */
+    async validateMetaObject(id) {
+        if (this.metaCache[id] === undefined) {
+            // if not cached -> getObject
+            const obj = await this.getObjectAsync(id);
+            if (obj && obj.type === 'meta') {
+                this.metaCache[id] = true;
```
Comment (Apollon77) [inline lib/objects/objectsInMemFileDB.js:115]: I miss a "resolve" here ... or ?!

File: lib/objects/objectsInMemFileDB.js [hunk 2]
```diff
@@ -53,6 +53,9 @@ class ObjectsInMemoryFileDB extends InMemoryFileDB {
 
         this.objectsDir = path.join(this.dataDir, 'files');
 
+        // cached meta objects for file operations
+        this.metaCache = {};
```
Comment (Apollon77) [inline lib/objects/objectsInMemFileDB.js:57]: Maybe name it better "existingMetaObjects" or such? ... Cache is relative unspecific for the use case (now that I see it in code ...)

Comment (Apollon77) [reply lib/objects/objectsInMemFileDB.js:57]: And we do not cache the object but just the "is meta type" status, so no cache ...

File: lib/objects/objectsInMemFileDB.js [hunk 3]
```diff
@@ -98,6 +101,27 @@ class ObjectsInMemoryFileDB extends InMemoryFileDB {
...
+     * @throws Error if id is invalid
+     */
+    async validateMetaObject(id) {
+        if (this.metaCache[id] === undefined) {
+            // if not cached -> getObject
+            const obj = await this.getObjectAsync(id);
+            if (obj && obj.type === 'meta') {
+                this.metaCache[id] = true;
+            } else {
+                this.metaCache[id] = false;
```
Comment (Apollon77) [inline lib/objects/objectsInMemFileDB.js:117]: Do we really need to store "false"? I personally would only store true, but in the end also works that way

File: lib/objects/objectsInMemFileDB.js [hunk 4]
```diff
@@ -98,6 +101,27 @@ class ObjectsInMemoryFileDB extends InMemoryFileDB {
...
+                return Promise.reject(`${id} is not an object of type "meta"`);
+            }
+        } else if (this.metaCache[id] === false) {
+            return Promise.reject(`${id} is not an object of type "meta"`);
+        }
+    }
```
Comment (Apollon77) [inline lib/objects/objectsInMemFileDB.js:123]: and also here a "resole" is needed for cases with true

Comment (Apollon77) [reply lib/objects/objectsInMemFileDB.js:123]: aahhh or is the promise only there for the "exception"?

File: lib/objects/objectsInMemFileDB.js [hunk 5]
```diff
@@ -547,6 +580,15 @@ class ObjectsInMemoryFileDB extends InMemoryFileDB {
             });
         }
 
+        try {
+            await this.validateMetaObject(id);
+        } catch (e) {
+            this.log.warn(`readFile will not read this file (${name}) in future versions: ${e}`);
```
Comment (Apollon77) [inline lib/objects/objectsInMemFileDB.js:586]: I would add the reason here "... because no corresponding meta object exists"

File: lib/objects/objectsInMemFileDB.js (hunk 1 above)
Comment (Apollon77) [reply lib/objects/objectsInMemFileDB.js:115]: aahhh or is the promise only there for the "exception"?

File: lib/objects/objectsInMemFileDB.js (hunk 5 above)
Comment (Apollon77) [reply lib/objects/objectsInMemFileDB.js:586]: ok, is in the error ;-)

File: lib/objects/objectsInMemFileDB.js (hunk 1 above)
Comment (foxriver76) [reply lib/objects/objectsInMemFileDB.js:115]: It's basically not needed, code is resolved with last line of code being successfully executed. It would also be the same to use `return` as `return Promise.resolve()`. And as we know return after the last line of code is unnecessary. But I am also not 100 % sure what is best practice here.

File: lib/objects/objectsInMemFileDB.js (hunk 2 above)
Comment (foxriver76) [reply lib/objects/objectsInMemFileDB.js:57]: Sounds good

File: lib/objects/objectsInMemFileDB.js (hunk 3 above)
Comment (foxriver76) [reply lib/objects/objectsInMemFileDB.js:117]: The logic here is: 
- If true `Information cached -> and its a meta object`,
- if false `Information cached -> and its not a meta object, so no need to use getObject, we already know that its not ok`, 
- if undefined: ` not cached yet` try to get information.

File: lib/objects/objectsInMemFileDB.js (hunk 1 above)
Comment (Apollon77) [reply lib/objects/objectsInMemFileDB.js:115]: @AlCalzone what do you think here? (My question was just becasue of "not knowing" :-)

File: lib/objects/objectsInMemFileDB.js (hunk 3 above)
Comment (Apollon77) [reply lib/objects/objectsInMemFileDB.js:117]: kk

File: lib/objects/objectsInMemFileDB.js (hunk 1 above)
Comment (AlCalzone) [reply lib/objects/objectsInMemFileDB.js]: Async methods implicitly return Promises with the value after `return`. They also implicitly return rejected Promises if you throw an Error.

File: lib/objects/objectsInMemFileDB.js [hunk 6]
```diff
@@ -98,8 +101,29 @@ class ObjectsInMemoryFileDB extends InMemoryFileDB {
...
+            // if not cached -> getObject
+            const obj = await this.getObjectAsync(id);
+            if (obj && obj.type === 'meta') {
+                this.metaCache[id] = true;
+            } else {
+                this.metaCache[id] = false;
+                return Promise.reject(`${id} is not an object of type "meta"`);
+            }
+        } else if (this.metaCache[id] === false) {
+            return Promise.reject(`${id} is not an object of type "meta"`);
```
Comment (AlCalzone) [inline lib/objects/objectsInMemFileDB.js]: Rejecting Promises with strings is an anti-pattern, because you never know if the caught exception is an Error or a string. Also, with strings you don't get any stacktrace for where the error comes from. Better to just
```js
throw new Error(`${id} is not an object of type "meta"`)
```
but the calling code needs to be updated to handle errors instead of strings so it does not print out the entire stack trace in a log message (line 452 and similar).

Comment (AlCalzone) [reply lib/objects/objectsInMemFileDB.js]: @Apollon77 what's your opinion on Errors vs strings?

File: lib/objects/objectsInMemFileDB.js (hunk 1 above)
Comment (Apollon77) [reply lib/objects/objectsInMemFileDB.js]: ok, so we can leave as it is  great!

File: lib/objects/objectsInMemFileDB.js (hunk 6 above)
Comment (Apollon77) [reply lib/objects/objectsInMemFileDB.js]: I like clean way (so Errors), but ioBroker uses both well mixed :-( In fact a normal "print(new Error("..."))" will not print stack trace by default and that sway it was never a topic ... All checks chec for "if (err)" so also here unimportant ...

I have no problem in controller to have strings

Comment (foxriver76) [reply lib/objects/objectsInMemFileDB.js]: I've added this to eslint and changed it in the PR.
