### PR TITLE
fix log message

### LINKED ISSUE #2088: Fix 'If something is not working...' Let's Encrypt message
Current message says to execute `iobroker admin.0 set --secure false` but this should be `iobroker set admin.0 --secure false`.

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #2088

### CODE REVIEW

File: packages/controller/src/lib/letsencrypt.js [hunk 1]
```diff
@@ -177,9 +177,9 @@ async function createServerAsync(app, settings, certificates, leSettings, log, a
                             httpServer.listen(settings.lePort, bind, () => {
                                 log.info(`Challenge server listening on port ${settings.lePort}`);
                                 log.info(
-                                    `If something is not working and your adapter is not reachable anymore you can turn off HTTPS with executing "iobroker ${
+                                    `If something is not working and your adapter is not reachable anymore you can turn off HTTPS with executing "iobroker set ${
```
Comment (Apollon77) [inline packages/controller/src/lib/letsencrypt.js:180]: hm ... if i look at it that way ... "adapter not reachable"? hhhmm ... "adapter webpage not reachable"? or such

Comment (foxriver76) [reply packages/controller/src/lib/letsencrypt.js:180]: yeah just fixed the command in the comment, we can rephrase if you like, makes sense

**Review by Apollon77 — APPROVED** [review]
