### PR TITLE
fixes for v4

### LINKED ISSUE #1698: Controller "setup first" creates additional instances also if one is already existing
setup.js L578+ ... we need to check if an instance already exists and only create an additional one if not

### LINKED ISSUE #1700: Dependency check on adapter delete is not checking correct and also delied deletion if more then 1 instance is there
> root@io-test4:~# iob delete admin.8
Delete instance "admin.8"
Cannot remove instance "admin.8", because instance "info" depends on it!

### PR DESCRIPTION
**Pull request by foxriver76**
- fixes #1698
- fixes #1700

### CODE REVIEW

File: packages/controller/lib/setup.js [hunk 1]
```diff
@@ -579,12 +579,28 @@ async function processCommand(command, args, params, callback) {
                             // And try to install each of them
                             for (const instance of initialInstances) {
                                 try {
-                                    const path = require.resolve(`${tools.appName}.${instance}`);
-                                    if (path) {
-                                        await install.createInstance(instance, {
-                                            enabled: true,
-                                            ignoreIfExists: true
+                                    let otherInstanceExists = false;
```
Comment (Apollon77) [inline packages/controller/lib/setup.js:582]: I would move that into "if path" because we only need to check if adater is installed ... or!?

**Review by Apollon77 — CHANGES_REQUESTED** [review]

File: packages/controller/lib/setup.js (hunk 1 above)
Comment (foxriver76) [reply packages/controller/lib/setup.js:582]: or checks vice versa both ok
