### PR TITLE
Try to fix type error and port notificationHandler

### LINKED ISSUE #1770: TypeError: Cannot convert undefined or null to object
Sentry Issue: [IOBROKER-JS-CONTROLLER-201](https://sentry.iobroker.net/organizations/iobroker/issues/7328/?referrer=github_integration)

```
TypeError: Cannot convert undefined or null to object
  ?, in Function.keys
  ?, in runMicrotasks
```

### PR DESCRIPTION
**Pull request by foxriver76**
closes #1770

### CODE REVIEW

File: packages/controller/src/lib/notificationHandler.ts [hunk 1]
```diff
@@ -4,24 +4,117 @@
...
+                    };
+                };
+            };
+        };
+    };
+}
+
+interface NotificationSetupObject {
+    [scope: string]: {
+        // @ts-expect-error: fixme the index signature overrides the named property type but on usage it works
```
Comment (foxriver76) [inline packages/controller/src/lib/notificationHandler.ts:83]: Any idea here @AlCalzone

**Comment by Apollon77** [comment]
LGTM, so @AlCalzone ts review open :-)

**Review by Apollon77 — APPROVED** [review]

File: packages/controller/src/lib/notificationHandler.ts [hunk 2]
```diff
@@ -4,24 +4,117 @@
...
-    /**
-     * Create a new instance of NotificationHandler
-     *
-     * @param {object} settings - settings like states/objects db
-     */
-    constructor(settings) {
+interface MultilingualObject {
+    en: string;
+    [otherLanguages: string]: string;
+}
```
Comment (AlCalzone) [inline packages/controller/src/lib/notificationHandler.ts:25]: I think this should be like `StringOrTranslated` [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/e1070c9c06fb32be5f1f8b1d8af8e9045c76a9e4/types/iobroker/objects.d.ts#L133-L139) but without the `string`.

We want to model that `en` is required and the other possible languages are optional, but no other languages, right?

File: packages/controller/src/lib/notificationHandler.ts [hunk 3]
```diff
@@ -4,24 +4,117 @@
...
+    name: MultilingualObject;
+    severity: Severity;
+    description: MultilingualObject;
+}
+
+interface NotificationSetupObject {
+    [scope: string]: {
+        name: MultilingualObject;
+        description: MultilingualObject;
+        categories: Record<string, NotificationSetupCategory>;
```
Comment (AlCalzone) [inline packages/controller/src/lib/notificationHandler.ts:93]: This is a bit inconsistent with the other nested objects which use an index signature.

File: packages/controller/src/lib/notificationHandler.ts [hunk 4]
```diff
@@ -4,24 +4,117 @@
...
+    [scope: string]: {
+        description: MultilingualObject;
+        name: MultilingualObject;
+        categories: {
+            [category: string]: {
+                description: MultilingualObject;
+                name: MultilingualObject;
+                severity: Severity;
+                instances: {
+                    [instance: string]: {
```
Comment (AlCalzone) [inline packages/controller/src/lib/notificationHandler.ts:72]: What kind of string is `instance` here?
`blabla.0`? or just `0`?

File: packages/controller/src/lib/notificationHandler.ts [hunk 5]
```diff
@@ -305,21 +404,19 @@ class NotificationHandler {
...
-    _parseText(scope, message) {
+    private _parseText(scope: string, message: string): string[] {
         const categories = [];
         if (this.setup[scope]) {
-            for (const category of Object.keys(this.setup[scope])) {
-                if (!this.setup[scope][category]) {
+            for (const category of Object.keys(this.setup[scope].categories)) {
+                if (!this.setup[scope].categories[category]) {
                     continue;
                 }
```
Comment (AlCalzone) [inline packages/controller/src/lib/notificationHandler.ts:416]:
```suggestion
            for (const [category, definition] of Object.entries(this.setup[scope].categories)) {
                if (!definition) continue;
```
and use `definition` below instead of repeating the indexed access.

How can `definition` be falsy anyways? Do we not check this when `this.setup[...]` is created?

File: packages/controller/src/lib/notificationHandler.ts [hunk 6]
```diff
@@ -361,13 +456,16 @@ class NotificationHandler {
...
+     * @param instanceFilter - instance of notifications
      */
-    getFilteredInformation(scopeFilter, categoryFilter, instanceFilter) {
-        const res = {};
+    getFilteredInformation(
+        scopeFilter: string | null | undefined,
+        categoryFilter: string | null | undefined,
+        instanceFilter: string | null | undefined
+    ): FilteredNotificationInformation {
+        const res: Partial<FilteredNotificationInformation> = {};
```
Comment (AlCalzone) [inline packages/controller/src/lib/notificationHandler.ts:468]:
```suggestion
        const res: FilteredNotificationInformation = {};
```
The `Partial` makes your life below harder because it adds `| undefined` to the type of the properties.

File: packages/controller/src/lib/notificationHandler.ts [hunk 7]
```diff
@@ -379,52 +477,55 @@ class NotificationHandler {
...
 
-                res[scope].categories[category] = { instances: {} };
-                res[scope].categories[category].description = this.setup[scope][category].description;
-                res[scope].categories[category].name = this.setup[scope][category].name;
-                res[scope].categories[category].severity = this.setup[scope][category].severity;
+                res[scope]!.categories[category] = {
+                    instances: {},
+                    description: this.setup[scope].categories[category].description,
+                    name: this.setup[scope].categories[category].name,
+                    severity: this.setup[scope].categories[category].severity
```
Comment (AlCalzone) [inline packages/controller/src/lib/notificationHandler.ts:497]: Please store `this.setup[scope].categories[category]` in a const at the start of the loop.

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: packages/controller/src/lib/notificationHandler.ts (hunk 2 above)
Comment (foxriver76) [reply packages/controller/src/lib/notificationHandler.ts:25]: good reminder, we already have it

File: packages/controller/src/lib/notificationHandler.ts (hunk 4 above)
Comment (foxriver76) [reply packages/controller/src/lib/notificationHandler.ts:72]: it can be `system.adapter.bla.0`, `bla.0` or `system.host.blub`

Comment (AlCalzone) [reply packages/controller/src/lib/notificationHandler.ts:67]: Hmm, so `ObjectIDs.Instance | ObjectIDs.Host`. May not be worth the effort though - you decide.

File: packages/controller/src/lib/notificationHandler.ts (hunk 2 above)
Comment (AlCalzone) [reply packages/controller/src/lib/notificationHandler.ts]: Hmm - is a plain `string` a valid option, i.e. is `StringOrTranslated` valid? Or does it have to be just the object part?
Because before your latest change, `string` was not allowed. Now it is.

Comment (foxriver76) [reply packages/controller/src/lib/notificationHandler.ts]: Ah thanks, no of course not. Now it should be correct.

**Review by AlCalzone — APPROVED** [review]
