### PR TITLE
Fix user

### LINKED ISSUE #952: Unable to login if username is uppercase
Hi,

If Username contains uppercase then "checkPassword" is not able to find the correct userobject.

https://github.com/ioBroker/ioBroker.js-controller/blob/656e7282ab5bb15a9af10c3e53498fcd51c3d888/lib/adapter.js#L627

It still doesn't work if toLowerCase is removed as admin also does that check before.
https://github.com/ioBroker/ioBroker.admin/blob/6d5163c40e14d721c94def994d433d5b3e4a4e2e/lib/web.js#L370

And even then permissions aren't loaded correctly. (calculcatePermissions and checkGroup)

I think either: 
1. Uppercase Usernames should be supported then all these checks need to remove the "toLowerCase()"
or
2. Uppercase Usernames should be banned then Admin should prevent creating these

### PR DESCRIPTION
**Pull request by foxriver76**
- introducing a username cache to retrive the real id by the username instead of guessing the id by the name
- fix clearing cache of `this.users` and `this.groups` due to the fact, that moved to object change handler from state change handler, they are only objects, so this has never worked correctly
- closes #952 
- Note: imho we should prevent identical usernames, at least in frontend, as this is currently possible, opinions?
Bildschirmfoto von 2020-06-24 22-49-27

### CODE REVIEW

File: lib/adapter.js [hunk 1]
```diff
@@ -4866,6 +4927,25 @@ function Adapter(options) {
...
     };
 
+    /**
+     * This method update the cached values in this.usernames
+     *
+     * @returns {Promise<void>}
+     */
+    const updateUsernameCache = async () => {
+        // make sure cache is cleared
+        this.usernames = {};
```
Comment (Apollon77) [inline lib/adapter.js:4937]: This can produice  edge cases or !? Because you clear cache and then start an async process to fill again. So this can produce multiple updates to be started "at the same time". But these are real edge caes I think ... But still to have the action "atomic" I would move the "set empty" into the async result method/callback. Yes then still stuff happens in parallel - but only if cache was empty

File: lib/adapter.js [hunk 2]
```diff
@@ -4866,6 +4927,25 @@ function Adapter(options) {
...
+        try {
+            // get all users
+            const obj = await this.getObjectListAsync({startkey: 'system.user.', endkey: 'system.user.\u9999'});
+            for (const row of obj.rows) {
+                this.usernames[row.value.common.name] = {id: row.id};
```
Comment (Apollon77) [inline lib/adapter.js:4942]: Can we trust that the name is always defined? Do we need emoty/null/undefined fallbacks?!

File: lib/adapter.js [hunk 3]
```diff
@@ -1511,6 +1561,10 @@ function Adapter(options) {
                     clearTimeout(initializeTimeout);
                     initializeTimeout = null;
                 }
+
+                // subscribe to user changes
+                adapterObjects.subscribe('system.user.*');
```
[the remark this answers is not in the document]
Comment (foxriver76) [reply lib/adapter.js:1566]: Not for the user/login changes, it would be possible to do the same for groups.

File: lib/adapter.js [hunk 4]
```diff
@@ -723,16 +750,31 @@ function Adapter(options) {
...
+
         if (user && !regUser.test(user)) {
-            user = 'system.user.' + user;
+            // its not yet a `system.user.xy` id, thus we assume it's a username
+            if (!this.usernames[user]) {
+                // we did not find the id of the username in our cache -> update cache
+                try {
+                    await updateUsernameCache();
+                } catch (e) {
+                    this.log.error(e);
```
[the remark this answers is not in the document]
Comment (foxriver76) [reply lib/adapter.js:768]: Yes it’s normal adapter logger like classic adapter.log.warn

File: lib/adapter.js [hunk 5]
```diff
@@ -1691,9 +1752,9 @@ function Adapter(options) {
                         }
                     }
 
-                    typeof options.objectChange === 'function' && setImmediate(() => options.objectChange(id, obj));
+                    typeof options.objectChange === 'function' && setImmediate(options.objectChange, id, obj);
                     // emit 'objectChange' event instantly
-                    setImmediate(() => this.emit('objectChange', id, obj));
+                    setImmediate(this.emit, 'objectChange', id, obj);
```
[the remark this answers is not in the document]
Comment (foxriver76) [reply lib/adapter.js:1757]: Has nothing to do with the this context because arrow functions are not changing the this context like classic anonymous functions

File: lib/adapter.js (hunk 2 above)
Comment (foxriver76) [reply lib/adapter.js:4942]: Hm probably not, this it’s currently always called inside try catch because I wanted to inform about this error, but an error in early iterations will stop the execution of this method and thus it may be more desirable to log an error inside the function if non existing property name.

File: lib/adapter.js (hunk 1 above)
Comment (foxriver76) [reply lib/adapter.js:4937]: Good point

File: lib/adapter.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (Apollon77) [reply lib/adapter.js:1757]: Yes. But if you remove the arrow Funktion the run context is different. Or?!

[the remark this answers is not in the document]
Comment (AlCalzone) [reply lib/adapter.js:1757]: This change will cause the this context to be lost. Passing the member function around is not the same as passing an arrow function around which calls this.something.

File: lib/adapter.js [hunk 6]
```diff
@@ -624,10 +626,21 @@ function Adapter(options) {
             throw new Error('checkPassword: no callback');
         }
 
-        user = (user || '').toString().replace(this.FORBIDDEN_CHARS, '_').replace(/\s/g, '_').replace(/\./g, '_').toLowerCase();
```
Comment (AlCalzone) [inline lib/adapter.js:627]: Do we now allow forbidden chars, spaces and dots in usernames?

File: lib/adapter.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (foxriver76) [reply lib/adapter.js:1757]: Don’t really get the difference regarding the `this` context  between calling the function inside an arrow function, which has no own `this` context and calling the function directly. Do you have an example?

[the remark this answers is not in the document]
Comment (AlCalzone) [reply lib/adapter.js:1757]:
```js
// repro.js
class Foo {
	constructor() {
		this.prop = "hallo";
	}

	method() {
		console.log(`this is ${JSON.stringify(this)}`);
		console.log(`this.prop is ${this.prop}`);
	}
}

const foo = new Foo();
setTimeout(() => foo.method(), 500);
setTimeout(foo.method, 1000);
```

```
$ node repro.js

this is {"prop":"hallo"}
this.prop is hallo

this is {"_idleTimeout":1000,"_idlePrev":null,"_idleNext":null,"_idleStart":19,"_repeat":null,"_destroyed":false}
this.prop is undefined
```

[the remark this answers is not in the document]
Comment (AlCalzone) [reply lib/adapter.js:1757]: If you don't use the arrow function, foo.method is called with `this` set to the timeout, not `foo`.

[the remark this answers is not in the document]
Comment (foxriver76) [reply lib/adapter.js:1757]: Yes, this is clear, however, it makes no difference for the `this.emit` call or do I miss out something?

[the remark this answers is not in the document]
Comment (AlCalzone) [reply lib/adapter.js:1757]: I think it should be fine for emit. 

But I still advocate for doing it with arrow functions consistently. Just in case someone uses this pattern in the future, does it like here for consistency and doesn't think twice about the this context.

File: lib/adapter.js (hunk 6 above)
Comment (foxriver76) [reply lib/adapter.js:627]: Have they ever been forbidden in usernames? I don't think so. At least you can easily create users with dots etc. in the username via admin

File: lib/adapter.js (hunk 5 above)
[the remark this answers is not in the document]
Comment (foxriver76) [reply lib/adapter.js:1757]: Changing it back just to not break something, but imo it should work with `emit`.

File: lib/adapter.js (hunk 6 above)
Comment (AlCalzone) [reply lib/adapter.js:627]: I'm not entirely sure, doesn't the username translate into a user object id? And the characters in FORBIDDEN_CHARS and spaces have been forbidden in object IDs for a while now. If its possible to create users with those names, we should raise an issue in admin IMO.

Comment (AlCalzone) [reply lib/adapter.js:627]: @Apollon77 ?

Comment (foxriver76) [reply lib/adapter.js:627]: this is what this PR is about, we no longer want to guess the id by the username how it is done atm, because it's also possible to have ids that have nothing to do with the username, , usernames with different forbidden chars can leadd to the same id, admin allows to configure id manually etc.. Thus, we want to cache the id related to every username.

Comment (AlCalzone) [reply lib/adapter.js:627]: Then we need to make sure that the ID is valid IMO

Comment (foxriver76) [reply lib/adapter.js:627]: due to the issues with github the commit is not displayed here yet, but theres an adaption in my fix-user branch, so probably just a matter of time

Comment (AlCalzone) [reply lib/adapter.js:627]: And what about whitespace chars? `\s`

Comment (foxriver76) [reply lib/adapter.js:627]: Are whitespaces forbidden in ids?

Comment (AlCalzone) [reply lib/adapter.js:627]: AFAIK yes. @Apollon77 ???

Comment (AlCalzone) [reply lib/adapter.js:627]: ok nevermind: https://github.com/ioBroker/ioBroker.js-controller/issues/341#issuecomment-527851885

Comment (AlCalzone) [reply lib/adapter.js:627]: LGTM then.

Comment (Apollon77) [reply lib/adapter.js:627]: sorry for answering nmow ... everything correct :-)
