### PR TITLE
fix a bug in autoSubscribe

### LINKED ISSUE #857: The checks in adapter.subscribeForeignStates (and similar) don't make sense
`pattern` may only be a string or string array (officially), but is internally called with RegExps.
https://github.com/ioBroker/ioBroker.js-controller/blob/acb2ce7c022e77b10086dd472ae6f3abea9c2ab6/lib/adapter.js#L7014 assumes that `pattern` is a string and will crash when called with an array.

https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L7034 checks if pattern is a RegExp, but does not check if it is an array of RegExps (the latter check would implicitly work for arrays btw).

https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L7039-L7048 assume again that pattern is an array of strings, but
https://github.com/ioBroker/ioBroker.js-controller/blob/master/lib/adapter.js#L7052-L7054 seem to convert RegExp arrays, so the above code would crash if that is the case.

@Apollon77 @foxriver76

### PR DESCRIPTION
**Pull request by foxriver76**
and add comment to fix #857

### CODE REVIEW

File: packages/adapter/lib/adapter/adapter.js [hunk 1]
```diff
@@ -8053,29 +8053,31 @@ function Adapter(options) {
             for (const autoSubEntry of this.autoSubscribe) {
                 if (typeof pattern === 'string' && (pattern === '*' || pattern.startsWith(`${autoSubEntry}.`))) {
                     // put this pattern into adapter list
-                    adapterStates.getState(`system.adapter.${autoSubEntry}.subscribes`, (err, state) => {
-                        state = {};
```
Comment (foxriver76) [inline packages/adapter/lib/adapter/adapter.js:8057]: yeah getState and then override

File: packages/adapter/lib/adapter/adapter.js [hunk 2]
```diff
@@ -8091,9 +8093,8 @@ function Adapter(options) {
                     .map(id => (typeof id === 'string' && !id.startsWith(ALIAS_STARTS_WITH) ? id : null))
                     .filter(id => id);
 
-                const promises = [];
-
                 for (let aliasPattern of pattern) {
+                    // TODO according to unsubscribe and jsdoc regexp is not allowed as array - we should return here with an error
```
Comment (foxriver76) [inline packages/adapter/lib/adapter/adapter.js:8097]: According to JSDOC we allow `string`, `string[]`, `RegExp`, also `unsubscribeForeignStates` does not support Array of Regexps code-wise, we should throw/error cb here. Other opinions? Also RegExp in general is weird if we just stringify it and then use it as pattern, because db code and Redis won't understand RegExp correctly

**Comment by foxriver76** [comment]
of course passing a regex as it is done in https://github.com/ioBroker/ioBroker.js-controller/blob/1360216c252693f9f7ed38e1ef385a5f4a4692d4/packages/adapter/lib/adapter/adapter.js#L8316 has never worked, because regex passed directly to https://github.com/ioBroker/ioBroker.js-controller/blob/1360216c252693f9f7ed38e1ef385a5f4a4692d4/packages/db-states-redis/lib/states/statesInRedisClient.js#L1031 where error cb is called and returned, but code ignores err cb until now.

**Comment by AlCalzone** [comment]
I could have sworn that I had an issue for this pattern/regexp weirdness. Can't find it right now but I remember I couldn't understand what was supposed to be going on there while writing the type definitions. I'm not sure if that ever worked.

**Comment by foxriver76** [comment]
> I could have sworn that I had an issue for this pattern/regexp

Yes it’s linked in the initial comment too, mainly the reason why I have looked into this part of the code

File: packages/adapter/lib/adapter/adapter.js (hunk 2 above)
Comment (Apollon77) [reply packages/adapter/lib/adapter/adapter.js:8097]: Then yes we should fix that. Hopefully we do not hit too many adapters

Comment (Apollon77) [reply packages/adapter/lib/adapter/adapter.js:8097]: Or maybe better then throwing adding a deprecation log and "ignore it" (because also former ist was kind of not effective"?

File: packages/adapter/lib/adapter/adapter.js [hunk 3]
```diff
@@ -8261,73 +8264,70 @@ function Adapter(options) {
...
+                            return;
+                        }
+                        let subs;
+                        try {
+                            subs = JSON.parse(state.val);
+                        } catch {
+                            logger.error(`${this.namespaceLog} Cannot parse subscribes for "${autoSub}.subscribes"`);
+                            return;
+                        }
+                        if (!subs[pattern]) {
```
Comment (Apollon77) [inline packages/adapter/lib/adapter/adapter.js:8286]: same here. subs can be non-object

File: packages/adapter/lib/adapter/adapter.js [hunk 4]
```diff
@@ -8261,73 +8264,70 @@ function Adapter(options) {
...
+                            return;
+                        }
+                        if (subs[pattern][this.namespace] === undefined) {
```
Comment (Apollon77) [inline packages/adapter/lib/adapter/adapter.js:8289]: for security handle cases where value is no number at all? else "--" will also fail?
I do not trust "state values" that much because anyone can write them

File: packages/adapter/lib/adapter/adapter.js [hunk 5]
```diff
@@ -8261,73 +8264,70 @@ function Adapter(options) {
...
-                            }
-                            this.outputCount++;
-                            adapterStates.setState(`system.adapter.${this.autoSubscribe[s]}.subscribes`, subs);
-                        });
+                        // if no other subs are there
+                        if (!Object.keys(subs[pattern]).length) {
+                            delete subs[pattern];
+                        }
+                        this.outputCount++;
+                        adapterStates.setState(`system.adapter.${autoSub}.subscribes`, subs);
```
Comment (Apollon77) [inline packages/adapter/lib/adapter/adapter.js:8302]: JSON.stringify(subs)? :-)

File: packages/adapter/lib/adapter/adapter.js [hunk 6]
```diff
@@ -8261,73 +8264,70 @@ function Adapter(options) {
...
                     }
                 }
             }
 
-            const promises = [];
```
Comment (Apollon77) [inline packages/adapter/lib/adapter/adapter.js:8305]: Can this have performance issues? In fact now runs sequencially ... before was parallel?

**Review by Apollon77 — CHANGES_REQUESTED** [review]

File: packages/adapter/lib/adapter/adapter.js [hunk 7]
```diff
@@ -8053,29 +8053,31 @@ function Adapter(options) {
...
+                        logger.error(`${this.namespaceLog} Cannot parse subscribes for "${autoSubEntry}.subscribes"`);
+                    }
 
-                        subs[pattern] = subs[pattern] || {};
-                        subs[pattern][this.namespace] = subs[pattern][this.namespace] || 0;
-                        subs[pattern][this.namespace]++;
-                        this.outputCount++;
-                        adapterStates.setState(`system.adapter.${autoSubEntry}.subscribes`, JSON.stringify(subs));
-                    });
+                    subs[pattern] = subs[pattern] || {};
```
[the remark this answers is not in the document]
Comment (foxriver76) [reply packages/adapter/lib/adapter/adapter.js:8071]: nothing changed here until yet.. so next line requires it to be an object

File: packages/adapter/lib/adapter/adapter.js (hunk 6 above)
Comment (foxriver76) [reply packages/adapter/lib/adapter/adapter.js:8305]: yes but most likely super minor

File: packages/adapter/lib/adapter/adapter.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (foxriver76) [reply packages/adapter/lib/adapter/adapter.js:8071]: it seems like it needs to be an object, which contains of namespace keys and these have numbers, see lines below

File: packages/adapter/lib/adapter/adapter.js (hunk 6 above)
Comment (foxriver76) [reply packages/adapter/lib/adapter/adapter.js:8293]: changed it back to pormises.all

File: packages/adapter/lib/adapter/adapter.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (foxriver76) [reply packages/adapter/lib/adapter/adapter.js:8067]: ahh.. so you mean because it depends on the state we should ensure that it's an object, not that number etc would be a valid sub?  ;-)

[the remark this answers is not in the document]
Comment (Apollon77) [reply packages/adapter/lib/adapter/adapter.js:8067]: I would add an 

if (!tools.isObject(subs)) subs = {}

File: packages/adapter/lib/adapter/adapter.js [hunk 8]
```diff
@@ -8229,93 +8228,105 @@ function Adapter(options) {
...
-                                return;
-                            }
+                        let state;
+                        try {
+                            state = await adapterStates.getState(`system.adapter.${autoSub}.subscribes`);
+                        } catch {
+                            // ignore
+                        }
+                        if (!state || !state.val) {
+                            return;
```
Comment (Apollon77) [inline packages/adapter/lib/adapter/adapter.js:8268]: ppuuh ... really return=? We are ina aoop ...hm ... continue better? (so in general=

File: packages/adapter/lib/adapter/adapter.js (hunk 7 above)
[the remark this answers is not in the document]
Comment (Apollon77) [reply packages/adapter/lib/adapter/adapter.js:8067]: ... like you did below :-)

**Review by Apollon77 — CHANGES_REQUESTED** [review]

File: packages/adapter/lib/adapter/adapter.js (hunk 8 above)
Comment (foxriver76) [reply packages/adapter/lib/adapter/adapter.js:8268]: probably better, also strange to return w/o calling cb

Comment (foxriver76) [reply packages/adapter/lib/adapter/adapter.js:8268]: probably for all returns in this loop

File: packages/adapter/lib/adapter/adapter.js [hunk 9]
```diff
@@ -8041,31 +8049,38 @@ function Adapter(options) {
...
+                    // validate that correct structure read from state.val
+                    if (!tools.isObject(subs)) {
+                        subs = {};
+                    }
 
-            // RegExp is allowed for alias only
-            if (pattern instanceof RegExp && pattern.toString().includes('alias')) {
-                logger.error(`${this.namespaceLog} Regexp is not supported for "subscribeForeignStates"`);
-                return tools.maybeCallbackWithError(callback, 'Regexp is not supported for "subscribeForeignStates"');
+                    if (!tools.isObject(subs)) {
```
Comment (Apollon77) [inline packages/adapter/lib/adapter/adapter.js:8072]: typo :-)

File: packages/adapter/lib/adapter/adapter.js [hunk 10]
```diff
@@ -8229,93 +8239,105 @@ function Adapter(options) {
...
+                        }
 
-                            // if no other subs are there
-                            if (!Object.keys(subs[pattern]).length) {
-                                delete subs[pattern];
-                            }
-                            this.outputCount++;
-                            adapterStates.setState(`system.adapter.${this.autoSubscribe[s]}.subscribes`, subs);
-                        });
+                        if (subs[pattern][this.namespace] <= 0) {
```
Comment (Apollon77) [inline packages/adapter/lib/adapter/adapter.js:8305]: I would out that in the "if number" above because only relevant then

**Review by Apollon77 — CHANGES_REQUESTED** [review]
