### PR TITLE
we also need to replace hostname in iobroker.json not only for instances

### LINKED ISSUE #1450: Restoring backup on different hostname (new docker container) fails/ shows strange behavior
I'm facing some strange behavior while restoring a backup in a new Docker container with a different hostname. 

What happened:
I started a simple ioBroker Docker container like this, installed and configured some adapters and generated a backup with backitup:
```
version: "2"
services:
  iobrokerold:
    container_name: iobrokerold
    image: buanet/iobroker:beta
    hostname: iobrokerold
    restart: always
    networks:
      bridge:
        ipv4_address: 172.19.0.2
    ports:
      - 8081:8081
    environment:
      - PACKAGES=nano
    volumes:
      - /volume1/docker/iobrokertemp_data:/opt/iobroker

networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
          ip_range: 172.19.0.1/24
```
Then I put the backup file into a new folder and started a new container with a different hostname (and name) like this:
```
version: "2"
services:
  iobrokernew:
    container_name: iobrokernew
    image: buanet/iobroker:beta
    hostname: iobrokernew
    restart: always
    networks:
      bridge:
        ipv4_address: 172.19.0.3
    ports:
      - 8081:8081
    environment:
      - PACKAGES=nano
    volumes:
      - /volume1/docker/iobrokertemp1_data:/opt/iobroker

networks:
  bridge:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
          gateway: 172.19.0.1
          ip_range: 172.19.0.1/24
```
The Docker container is designed to restore the Backupfile into a fresh installation of ioBroker automatically (on startup: `iob restore 0` then starting ioBroker) 
During startup ioBroker throws something like:
```
================================== > LOG REDIRECT system.adapter.admin.0 => true [starting],
host.iobrokerold check instance "system.adapter.javascript.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.admin.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.backitup.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.dwd.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.discovery.0" for host "iobrokernew",
host.iobrokerold check instance "system.adapter.history.0" for host "iobrokernew"
```
As you see `host.iobrokerold` seems not to be renamed correctly while the instances seems to be. (BTW: ioBroker admin is not accessible at this moment) 
So i checked the admin.0 objects
```
root@iobrokernew:/opt/iobroker# iobroker object get system.adapter.admin.0 --pretty | grep -oP '(?<="host": ")[^"]*'
iobrokernew
```
looks good so far. 
Then I checked iobroker.json
```
{
  "system": {
    "memoryLimitMB": 0,
    "hostname": "iobrokerold",
...
```
hostname still remains old! Doesn't look correct to me. 

To get ioBroker back running I stopped ioBroker, tried `iob host iobrokerold`, and restarted the container. 
```
root@iobrokernew:/opt/iobroker# iob host iobrokerold
Host "iobrokerold" successfully renamed to "iobrokernew".
No instances found for host "iobrokerold"!
```
This worked. 

------------------------

To fix this "bug" I tried to call `iob host iobrokerold` from the startupscript directly after the restore. But this leads to:
` A host with the name "iobrokernew" already exists!`

It seems like ioBroker needs to be started for one time after the restore to make the host command running. 

All together some kind of strange. :) Does someone have a good explanation for this? 

Regards,
André

### PR DESCRIPTION
**Pull request by foxriver76**
- fixes #1450

### CODE REVIEW

File: packages/controller/lib/setup/setupBackup.js [hunk 1]
```diff
@@ -649,36 +649,38 @@ class BackupRestore {
...
-        console.log('host.' + hostname + ' Clear all objects and states...');
+        console.log(`host.${hostname} Clear all objects and states...`);
         this.cleanDatabase(false, () => {
-            console.log('host.' + hostname + ' done.');
+            console.log(`host.${hostname} done.`);
             // upload all data into DB
-            // restore ioBorker.json
-            if (restore.config) {
+            // restore iobroker.json
+            if (restore.config && restore.config.system) {
```
Comment (Apollon77) [inline packages/controller/lib/setup/setupBackup.js:672]: Ok, in fcat "system" should be always there, but now - if system is missing - the file would not get written at all ... 
I think the "if system" should be an if inside the if restore.config AND also checking that hostname is set at all .. because if hostname empty in current file then should also not be needed to be persisted or?!

**Review by Apollon77 — CHANGES_REQUESTED** [review]

File: packages/controller/lib/setup/setupBackup.js (hunk 1 above)
Comment (foxriver76) [reply packages/controller/lib/setup/setupBackup.js:672]: It’s not the main point of this pr, just added the check because I access properties of system

**Comment by Apollon77** [comment]
LGTM
