### PR TITLE
if we cannot initialize logger, we wont start

### LINKED ISSUE #1638: `logger` is undefined, but used when loading it fails with a different error than `EACCES_LOG`.
See
https://github.com/ioBroker/ioBroker.js-controller/blob/fd9503254056dd5fba57972394c61bdd5d04fddb/main.js#L4554-L4557

and the following lines.

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1638

### CODE REVIEW

**Comment by Apollon77** [comment]
LGTM

File: packages/controller/main.js [hunk 1]
```diff
@@ -5352,7 +5352,8 @@ function init(compactGroupId) {
                 `${hostLogPrefix} Your logging path "${e.path}" was invalid, it has been changed to "${fixedLogPath}"`
             );
         } else {
-            console.error(`Error initializing logger: ${e.message}`);
+            // without logger multiple things will have undefined behavior and probably more is wrong -> do not start
+            throw new Error(`Error initializing logger: ${e.message}`);
```
Comment (AlCalzone) [inline packages/controller/main.js:5356]:
```diff
- e.message
+ e.stack
```
to see where the error is coming from.

Also, does throwing here do a clean shutdown or should we just log and `process.exit` instead?

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: packages/controller/main.js (hunk 1 above)
Comment (foxriver76) [reply packages/controller/main.js:5356]: Makes sense for these "strange" errors, I assume it makes no difference but we can call process exit
