### PR TITLE
Fix mh add

### LINKED ISSUE #1356: Check if host exists if add instance to specific host.
The command 
`ioBroker a socketio --host myOtherHost`
Does not check if the host myOtherHost exists. But should do.

### PR DESCRIPTION
**Pull request by foxriver76**
- fixed a bug which lead to an infinite loop if the repo was invalid and no cached sources available
- check host existence before adding instance -> fixes #1356

### CODE REVIEW

File: lib/setup.js [hunk 1]
```diff
@@ -2590,19 +2605,23 @@ function getRepository(repoUrl, params, callback) {
...
                                     name: tools.appName
                                 }, (_err, sources, sourcesHash) => {
-                                    repos.native.repositories[active].json = sources;
-                                    repos.native.repositories[active].hash = sourcesHash;
-                                    repos.from = 'system.host.' + tools.getHostName() + '.cli';
-                                    repos.ts = new Date().getTime();
-                                    // Store uploaded repo
-                                    objects.setObject('system.repositories', repos, () => void callback(null, sources));
+                                    if (_err && !sources) {
+                                        callback(_err, sources);
```
Comment (foxriver76) [inline lib/setup.js:2609]: if no cached sources -> pass the error to the cb, so it can be detected
