### PR TITLE
prevent crash on creating instanceobjects

### LINKED ISSUE #2635: [enhancement]: Crashinfo / Error with missing _id: in io-package is not helpful
### No existing issues.

- [X] There is no existing issue for my request.

### Description

If io-package contains an invalid instanceObject definition with missing _id clause, the error message is not very helpful.

io-package - **note _id info.connection is missing**:
```
  "instanceObjects": [
    {
      "_id": "info",
      "type": "channel",
      "common": {
        "name": "Information"
      },
      "native": {}
    },
    {
      "type": "state",
      "common": {
        "role": "indicator.connected",
        "name": "Device or service connected",
        "type": "boolean",
        "read": true,
        "write": false,
        "def": false
      },
      "native": {}
    }
  ]
```

error:

```
2024-03-13 19:59:17.384  - error: heizoel24-mex.0 (2193) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2024-03-13 19:59:17.385  - error: heizoel24-mex.0 (2193) unhandled promise rejection: Cannot read properties of undefined (reading 'startsWith')
2024-03-13 19:59:17.[387](https://github.com/ltspicer/ioBroker.heizoel24-mex/actions/runs/8270781685/job/22629101675#step:2:403)  - error: heizoel24-mex.0 (2193) TypeError: Cannot read properties of undefined (reading 'startsWith')
    at Heizoel24Mex._createInstancesObjects (/tmp/test-iobroker.heizoel24-mex/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:9186:30)
    at /tmp/test-iobroker.heizoel24-mex/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8984:28
    at PluginHandler.initPlugins (/tmp/test-iobroker.heizoel24-mex/node_modules/@iobroker/plugin-base/lib/PluginHandler.js:150:64)
    at Immediate.<anonymous> (/tmp/test-iobroker.heizoel24-mex/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:8842:32)
    at process.processImmediate (node:internal/timers:476:21)
2024-03-13 19:59:17.387  - error: heizoel24-mex.0 (2193) Cannot read properties of undefined (reading 'startsWith')
```

Please issue a clear message that something is wrong with object definiion or io-package.
Maybe checking thet _id is present and valid could be done ?

### Why?

Locating the erroro was only possible by checking comit history as aneither tests nor repo tests reported it. And manual review ob io.package die not recognize the missing_id too

### How?

_No response_

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #2635

### CODE REVIEW

File: packages/adapter/src/lib/adapter/adapter.ts [hunk 1]
```diff
@@ -11987,63 +11987,65 @@ export class AdapterClass extends EventEmitter {
             for (const instObj of instanceObj.instanceObjects) {
                 const obj: IoPackageInstanceObject & { state?: unknown } = instObj;
 
+                // the object comes from non-checked io-package, so treat the id as unknown
+                if (!obj || typeof (obj._id as unknown) !== 'string' || (!obj._id && obj.type !== 'meta')) {
```
Comment (Apollon77) [inline packages/adapter/src/lib/adapter/adapter.ts:11991]: Ok, so only allowed on top level with empty _id is meta ... k

**Review by Apollon77 — APPROVED** [review]

File: packages/adapter/src/lib/adapter/adapter.ts (hunk 1 above)
Comment (foxriver76) [reply packages/adapter/src/lib/adapter/adapter.ts:11991]: yes, you can make e.g. `hm-rpc.0` a meta object this way. It was that way before.
