### PR TITLE
fix host this

### LINKED ISSUE #920: Probleme mit "iobroker host [hostname]"
Moin,
wie wir in #286 schon einmal zerpflückt haben, nutze ich in meinem ioBroker Docker Image den Befehl "iobroker host [hostname] um den beim der Installation von ioBroker während des Docker Build Prozess hinterlegten "temporären" Hostnamen zu ersetzen. 

Bis vor einigen Tagen hat dies auch wunderbar geklappt. Wie allerdings z.B. in https://github.com/buanet/docker-iobroker/issues/100 gemeldet gibt es seit kurzem vermehrt Fälle in denen der Aufruf von "iobroker host [hostname]" beim ersten Start des Containers die Fehlermeldung
`No instances found for host "[hostname]"`
nach sich zieht und der Hostname dementsprechend nicht korrigiert wird.
Ein Blick in die objects.json bestätigt das. 

Bei der Analyse zu diesem Fehlerbild ist mir durch Zufall ein etwas älteres Image in die Hände gefallen bei dem der Fehler (noch) nicht auftritt. Das Image ist im Großen und Ganzen gleich (dockerfile, schripts) allerdings wurde es mit einer älteren Node Version erstellt (v12.16.8). Bei Tests mit Images die Node Versionen v12.17.0 und v12.18.0 enthielten tritt der Fehler auf. 
Seltsam ist, dass der Fehler auch bei aktuellen Versionen von Node v10 auftritt. z. B. v10.20.1.
Allerdings ist des m. E. durchaus möglich dass trotzdem ein Zusammenhang mit der Node Version bestehen kann, z.B. wenn ein (Security)Fix sowohl in Node 12 als auch in node 10 implementiert worden ist.

Kann es sein dass die Node Version Auswirkungen auf den Befehl "iobroker host ..." hat? Und wie schaut es mit anderen Umgebungen aus, gibt es da vielleicht auch Probleme?

Und Zusatzfrage: 
Als temporären Workaround (und vielleicht zukünftige Lösung zur Vermeidung des "iobroker host ..." Befehls) baue ich gerade das Startscript des Containers etwas um, sodass statt "iobroker host ..." einfach der Hostname in states.json und objects.json ersetzt wird. Ist das aus ioBroker Sicht eine gute Idee?

Danke!

MfG,
André

### PR DESCRIPTION
**Pull request by foxriver76**
- most likely fixes #920 
- when `enumInstances` is called with adapter being undefined it checked for `startsWith('system.adapter.undefined.')` instead of `startsWith('system.adapter.')`

### CODE REVIEW

File: lib/cli/cliTools.js [hunk 1]
```diff
@@ -66,7 +66,7 @@ function getInstanceName(instanceObjID) {
 function enumInstances(objects, adapter) {
     const startkey = 'system.adapter.' + (adapter ? adapter + '.' : '');
     return enumObjects(objects, 'instance', startkey)
-        .then(data => data.filter(it => it._id.startsWith('system.adapter.' + adapter + '.')));
+        .then(data => data.filter(it => it._id.startsWith(startkey)));
```
Comment (AlCalzone) [inline lib/cli/cliTools.js:69]: I'm not sure if we even need this filter call anymore. Shouldn't `enumObjects` already return all ids that start with `startKey`?

File: lib/cli/cliHost.js [hunk 2]
```diff
@@ -167,12 +167,14 @@ module.exports = class CLIHost extends CLICommand {
                     return void callback(30);
                 }
 
+                /*
+                // TODO: we allow migration to already existing host - if no problem occurs, remove lines after September 2020
```
Comment (AlCalzone) [inline lib/cli/cliHost.js:171]: Is it possible that not checking this opens up the possibility of having two identically-named hosts?

File: lib/cli/cliTools.js (hunk 1 above)
Comment (foxriver76) [reply lib/cli/cliTools.js:69]: True

File: lib/cli/cliHost.js (hunk 2 above)
Comment (foxriver76) [reply lib/cli/cliHost.js:171]: Also thought about this, and this could of course be a problem and I don't see a possibility to check it and still allow the migration.

File: lib/cli/cliTools.js (hunk 1 above)
Comment (foxriver76) [reply lib/cli/cliTools.js]: We could actively ask the user, but I am approx. 100 % sure somebody will still manage to have multihost with identical names. So better prevent it like before.. at least for now

File: lib/cli/cliHost.js (hunk 2 above)
Comment (foxriver76) [reply lib/cli/cliHost.js]: We could actively ask the user, but I am approx. 100 % sure somebody will still manage to have multihost with identical names. So better prevent it like before.. at least for now
