### PR TITLE
do not throw error on deletion

### LINKED ISSUE #2264: Objects 127.0.0.1:60780 Error from InMemDB
Hello all,

I have updated to version 5 of the controller and at the first start the following warning in the log:

`Objects 127.0.0.1:60780 Error from InMemDB: Error: Not exists at ObjectsInMemoryServer._delObject (/opt/iobroker/node_modules/@iobroker/db-objects-file/src/lib/objects/objectsInMemFileDB.js:927:19) at RedisHandler.<anonymous> (/opt/iobroker/node_modules/@iobroker/db-objects-jsonl/src/lib/objects/objectsInMemServerRedis.js:668:26) at RedisHandler.emit (node:events:513:28) at RedisHandler.emit (node:domain:489:12) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-base/src/lib/redisHandler.ts:209:37) at processImmediate (node:internal/timers:476:21)`

Should this be relevant for me?
Best regards
Christian

### PR DESCRIPTION
**Pull request by foxriver76**
- this harmonizes behavior between redis and file db
- some small refactoring
- closes #2264

### CODE REVIEW

File: packages/db-objects-file/src/lib/objects/objectsInMemFileDB.js [hunk 1]
```diff
@@ -38,17 +38,21 @@ class ObjectsInMemoryFileDB extends InMemoryFileDB {
                 this.log.silly(`${this.namespace} objects change: ${id} ${JSON.stringify(this.change)}`);
             };
         }
+
+        this.META_ID = '**META**';
```
Comment (Apollon77) [inline packages/db-objects-file/src/lib/objects/objectsInMemFileDB.js:42]: I would more do that as a normal "file" constant rather then a class property because only used here

**Review by Apollon77 — APPROVED** [review]
