### PR TITLE
Port setup.js to ts and fix file sync not working for jsonl

### LINKED ISSUE #2026: File Sync is only available when database type "file" is used
Bezug nehmend auf das folgende Issue im VIS Editor, hier nochmal der Hinweis auf den folgenden Fehler: 

```
C:\iobroker\GLT>iob file sync
File Sync is only available when database type "file" is used.
```

[Apollon77](https://github.com/Apollon77) commented [1 hour ago](https://github.com/ioBroker/ioBroker.vis/issues/538#issuecomment-1288546217)
C:\iobroker\GLT>iob file sync File Sync is only available when database type "file" is used.

Mist haben wir was vergessen bei jsonl ... Bitte leg mal ein js.controller issue an. Muss auch bei jsonl gehen

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #2026

### CODE REVIEW

**Comment by foxriver76** [comment]
Todos especially with the file operation callbacks are somewhat inconsistent, I don't think that this has ever worked as coded.

**Comment by foxriver76** [comment]
@Apollon77

File: packages/controller/src/lib/setup.ts [hunk 1]
```diff
@@ -3066,25 +3097,31 @@ async function checkSystemOffline(onlyCheck) {
...
         logNamespace: `host.${hostname}`,
         scope: 'controller',
         log: {
             // cli should be clean, only log warn/error
-            silly: _msg => {},
-            debug: _msg => {},
-            info: _msg => {},
-            warn: msg => console.log(msg),
-            error: msg => console.log(msg)
+            silly: (_msg: string) => {
```
Comment (Apollon77) [inline packages/controller/src/lib/setup.ts:3113]: In fact we could hve a "defaultLogger" and use it in all 4 places ... then it would be eaier dto change it when needed? (Maybe then also addd a --debug parameter hwich enableds mroe logging? (not needingly this PR)

**Review by Apollon77 — APPROVED** [review]

**Comment by foxriver76** [comment]
MAybe here a short review from @AlCalzone would be great

**Comment by foxriver76** [comment]
Maybe in the next days you have some time for a review @AlCalzone? Else it will end up in merge without a profound TS review.

**Comment by foxriver76** [comment]
ping @AlCalzone ;-)

File: packages/cli/src/lib/cli/cliCommand.ts [hunk 2]
```diff
@@ -4,15 +4,17 @@ import type { Client as StatesClient } from '@iobroker/db-states-redis';
 export type DBConnectCallback = (
     objects: ObjectsClient,
     states: StatesClient,
-    isOffline?: boolean,
-    objectsDBType?: string
+    isOffline: boolean,
+    objectsDBType: string,
+    /** the iobroker.json config file */
+    config?: Record<string, any>
 ) => void;
```
Comment (AlCalzone) [inline packages/cli/src/lib/cli/cliCommand.ts:11]: I think it would be nice to have a single callback return argument with an object containing those values. That way you can just pick the value you need instead of having to look up their order and select the correct ones.

File: packages/common/src/lib/common/tools.ts [hunk 3]
```diff
@@ -2080,7 +2077,7 @@ export async function getHostInfo(
 
     // Check if repositories exists
     const allRepos: Record<string, any> = {};
-    if (systemRepos && systemRepos.native && systemRepos.native.repositories) {
+    if (systemRepos?.native?.repositories && systemConfig) {
```
Comment (AlCalzone) [inline packages/common/src/lib/common/tools.ts:2080]:
```suggestion
    if (systemRepos?.native?.repositories && systemConfig?.common) {
```
or is that never undefined?

File: packages/controller/src/lib/setup.ts [hunk 4]
```diff
@@ -470,42 +483,47 @@ function initYargs() {
...
- * @param {any[]} args - arguments passed to yargs
- * @param {object} params - object with parsed params by yargs, e. g. --force is params.force
- * @param {(exitCode?: number) => void} callback
+ * @param command - command to execute
+ * @param args - arguments passed to yargs
+ * @param params - object with parsed params by yargs, e. g. --force is params.force
+ * @param callback
  */
-async function processCommand(command, args, params, callback) {
+async function processCommand(
```
Comment (AlCalzone) [inline packages/controller/src/lib/setup.ts:514]: Looks like this may need overloads?

File: packages/controller/src/lib/setup.ts [hunk 5]
```diff
@@ -561,6 +577,7 @@ async function processCommand(command, args, params, callback) {
             Objects = getObjectsConstructor();
             const repoUrl = args[0]; // Repo url or name
             dbConnect(params, async (_objects, _states) => {
+                // eslint-disable-next-line @typescript-eslint/no-var-requires
                 const Repo = require('./setup/setupRepo.js');
```
Comment (AlCalzone) [inline packages/controller/src/lib/setup.ts:581]: You could replace this with an `await import` like in the `'setup'` case

File: packages/controller/src/lib/setup.ts [hunk 6]
```diff
@@ -660,6 +677,7 @@ async function processCommand(command, args, params, callback) {
 
                         // we update existing things, in first as well as normnal setup
                         // Rename repositories
+                        // eslint-disable-next-line @typescript-eslint/no-var-requires
```
Comment (AlCalzone) [inline packages/controller/src/lib/setup.ts:680]: await import maybe?

**Review by AlCalzone — COMMENTED** [review]
A few minor things. What bugs me the most is that every use of `objects` and `states` currently needs a non-null assertion (possible TypeError).
I guess we should either not have them as global variables, and instead have them created or returned by `dbConnect`.
Then you can be sure they are defined without having to convince TypeScript.

File: packages/common/src/lib/common/tools.ts (hunk 3 above)
Comment (foxriver76) [reply packages/common/src/lib/common/tools.ts:2080]: According to types `system.config` always has a common property

Comment (foxriver76) [reply packages/common/src/lib/common/tools.ts:2080]: According to types yes, always defined

File: packages/controller/src/lib/setup.ts (hunk 4 above)
Comment (foxriver76) [reply packages/controller/src/lib/setup.ts:514]: no really, we only have one call in this file. I removed the unnecessary sanity check juggle

File: packages/controller/src/lib/setup.ts (hunk 6 above)
Comment (foxriver76) [reply packages/controller/src/lib/setup.ts:680]: same as above, I would like to, but as it is plain js he does not infer anything and we need an expect error a line below

**Comment by foxriver76** [comment]
short re-review @AlCalzone?

File: packages/cli/src/lib/cli/cliCert.js [hunk 7]
```diff
@@ -65,7 +65,9 @@ module.exports = class CLICert extends CLICommand {
             certName = 'defaultPublic';
         }
         const { callback, dbConnect } = this.options;
-        dbConnect((objects, _states, _isOffline, _objectDbType, _config) => {
+        dbConnect(params => {
+            const { objects } = params;
```
Comment (AlCalzone) [inline packages/cli/src/lib/cli/cliCert.js:69]: yeah that is much nicer

File: packages/cli/src/lib/cli/cliHost.ts [hunk 8]
```diff
@@ -153,7 +155,9 @@ export class CLIHost extends CLICommand {
      */
     renameHost(oldHostname: string | undefined, newHostname: string): void {
         const { callback, dbConnect, showHelp } = this.options;
-        dbConnect(async (objects, states, isOffline) => {
+        dbConnect(async params => {
+            const { isOffline, objects } = params;
```
Comment (AlCalzone) [inline packages/cli/src/lib/cli/cliHost.ts:159]: Could also do:
```suggestion
        dbConnect(async ({ isOffline, objects }) => {
```

**Review by AlCalzone — APPROVED** [review]
