### PR TITLE
Detct restart loop and stop restarting after 3 crashes

### LINKED ISSUE #1128: Prevent adapter error restart loops
The js-controller should basically already prevent adapter start loops when the adapter never reports an alive after the start. In such cases the adapter is stopped after 3 tries.

But when the adapter basically starts but then crash some seconds later because of a connection issue or such then the adapter runs into an crash-restart-loop.

We should add a detection for this for deamon type adapters if they run "only too short" and crash then (so not a normal end). Time could be 30-60s (??)

What do you think?

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1128
- if between crashes adapter runs for ~10 minutes, we say it's no restart loop

### CODE REVIEW

File: main.js [hunk 1]
```diff
@@ -3371,21 +3371,60 @@ function startInstance(id, wakeUp) {
...
+                                    if (procs[id].crashResetTimer) {
+                                        logger.debug(`${hostLogPrefix} Reset crash timer of ${id}, to be initialized anew`);
+                                        clearTimeout(procs[id].crashResetTimer);
+                                    }
+
+                                    // after 10 minutes without crash, we reset counter
+                                    logger.debug(`${hostLogPrefix} Initialize crash timer of ${id}`);
+                                    procs[id].crashResetTimer = setTimeout(() => {
+                                        logger.debug(`${hostLogPrefix} Cleared crash counter of ${id}, because 10 minutes no crash`);
+                                        procs[id].crashCount = 0;
```
Comment (Apollon77) [inline main.js:3389]: Better check here that procs[id] still exists ... there can be caes wherethe instance was moved to an other host in the meantime

**Review by Apollon77 — CHANGES_REQUESTED** [review]

**Comment by Apollon77** [comment]
Oohh BTW ... maybe also make sure to clear the time in the cases where procs[id] is deleted or overwritten (Should be "on object change logic)

File: main.js [hunk 2]
```diff
@@ -3386,7 +3396,10 @@ function startInstance(id, wakeUp) {
                                     logger.debug(`${hostLogPrefix} Initialize crash timer of ${id}`);
                                     procs[id].crashResetTimer = setTimeout(() => {
                                         logger.debug(`${hostLogPrefix} Cleared crash counter of ${id}, because 10 minutes no crash`);
-                                        procs[id].crashCount = 0;
```
Comment (Apollon77) [inline main.js]: We should also set procs[id].crashResetTimer = null when it is fired

**Review by Apollon77 — CHANGES_REQUESTED** [review]

File: main.js (hunk 2 above)
Comment (foxriver76) [reply main.js]: we always clear in exit handler, on crash https://github.com/ioBroker/ioBroker.js-controller/pull/1129/files#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aR3384-R3389 here and immediately set timer again because crash ;-) so no need to delete

on non-crash exit it will also be cleared and w/o crash no timer will be started again https://github.com/ioBroker/ioBroker.js-controller/pull/1129/files#diff-58417e0f781b6656949d37258c8b9052ed266e2eb7a5163cad7b0863e6b2916aR3400-R3403

**Review by Apollon77 — APPROVED** [review]
