### PR TITLE
determine the corret package dir if local rebuild needed

### LINKED ISSUE #1659: Local rebuild not working
Wrong directory is used:

```
2022-01-09 22:54:13.116  - info: host.io-test4 iobroker npm-rebuild: Rebuilding native modules in /opt/iobroker/node_modules/@abandonware/bluetooth-hci-socket/lib/binding/bluetooth_hci_socket.node ...
```

```
2022-01-09 22:54:13.130  - error: host.io-test4 iobroker npm-rebuild: Uncaught Rejection: Error: Command failed with ENOTDIR: npm rebuild --loglevel errorspawn ENOTDIR    at ChildProcess.spawn (internal/child_process.js:405:11)    at spawn (child_process.js:677:9)    at Object.spawnWithSignal [as spawn] (child_process.js:911:17)    at Object.execa [as default] (/opt/iobroker/node_modules/@alcalzone/pak/node_modules/execa/index.js:83:26)    at Npm.command (/opt/iobroker/node_modules/@alcalzone/pak/build/lib/package-managers/npm/index.js:152:40)    at Npm.rebuild (/opt/iobroker/node_modules/@alcalzone/pak/build/lib/package-managers/npm/index.js:227:21)    at Object.rebuildNodeModules (/opt/iobroker/node_modules/@iobroker/js-controller-common/lib/common/tools.js:1559:16)    at async processCommand (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup.js:854:28)
```
We can not use the found path directly but need to find the "module root":
* search to LAST node_modules in the string
* check if next Path entry starts with @ 
* if yes: include this and the next entry
* if no: just include this

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1659

### CODE REVIEW

File: packages/controller/main.js [hunk 1]
```diff
@@ -5679,6 +5669,36 @@ function init(compactGroupId) {
...
+/**
+ * Parses out the rebuild path from an error log
+ *
+ * @param {string} text - log text
+ * @return {string | undefined}
+ * @private
+ */
+function _determineRebuildPathFromLog(text) {
+    // extract rebuild path - it is always between the only two single quotes
+    const matches = text.match(/'.+'/g);
```
Comment (Apollon77) [inline packages/controller/main.js:5681]: Why not directly use /'(.+)'/g) ... then you directl have the value in matches[2] ?! YOu do dnot need to do the string replace then

File: packages/controller/main.js [hunk 2]
```diff
@@ -5679,6 +5669,36 @@ function init(compactGroupId) {
...
+        // remove the quotes
+        let rebuildPath = matches[0].replace(/'/g, '');
+        if (path.isAbsolute(rebuildPath)) {
+            // we have found a module which needs rebuild - we need to find deepest pack.json
+            rebuildPath = path.dirname(rebuildPath);
+            const rootDir = path.parse(process.cwd()).root;
+
+            while (rebuildPath !== rootDir) {
+                if (fs.pathExistsSync(path.join(rebuildPath, 'package.json'))) {
+                    return rebuildPath;
```
Comment (Apollon77) [inline packages/controller/main.js:5693]: Maybe add a path.normalize? Then you do not have a /bla/blubb/falsel/../../.. construct but something "real" :-)

Comment (Apollon77) [reply packages/controller/main.js:5693]: Or mnormalize directly on path.join

Comment (foxriver76) [reply packages/controller/main.js:5693]: The return of path join .. does not contain ..

File: packages/controller/main.js (hunk 1 above)
Comment (foxriver76) [reply packages/controller/main.js:5681]: `/'(.+)'/g` actually returns the same

Comment (foxriver76) [reply packages/controller/main.js:5681]: with named capture group it would be a one liner but imo harder to read and more extensive checks

```
    const matches = text.match(/'(?<rebuildPath>.+)'/);
```

thus i would keep it

File: packages/controller/main.js (hunk 2 above)
Comment (Apollon77) [reply packages/controller/main.js:5693]: Cool ... learned something :-)

File: packages/controller/main.js (hunk 1 above)
Comment (foxriver76) [reply packages/controller/main.js:5681]: ah edit: okay with your approach correct in matches[**1**] is correct but I think forcing one match is nice too
