### PR TITLE
setObjectNotExists needs to return id

### LINKED ISSUE #1851: Prevent unload call when ready was no emitted on adapter
It seems that there exists an edge case that could cause (most likely in exeption cases) a call to "stop()" in adapter.js which is then triggering "unload".
Issue is that this also seems to be possible to happen before "utils" was initialized which also means that "ready" was never emitted.

We should guard that:
* a stop call do not trigger unload if "ready" was never triggered
* a ready evet is never triggered when an exceptions happened before so that adater is in "stopInProgress" mode

### LINKED ISSUE #1852: setObjectNotExists sometimes do not return id
https://github.com/ioBroker/ioBroker.js-controller/blob/ef364284a964d6854558dc6ce16647f2993ed126/packages/adapter/src/lib/adapter/adapter.js#L3605 (after "null" should be a {id: '...'} :-(

### PR DESCRIPTION
**Pull request by foxriver76**
and do not call ready if stopping, do not trigger unload if we were never ready

closes #1852 
closes #1851

### CODE REVIEW

File: packages/adapter/src/lib/adapter/adapter.js [hunk 1]
```diff
@@ -9108,28 +9108,31 @@ function Adapter(options) {
...
-                            this.emit('ready');
-                        } else {
-                            typeof options.reconnect === 'function' && options.reconnect();
-                            this.emit('reconnect');
-                        }
+                if (!stopInProgress) {
+                    // auto oStates
+                    if (options.states) {
+                        this.getStates('*', null, (err, _states) => {
+                            this.oStates = _states;
```
Comment (Apollon77) [inline packages/adapter/src/lib/adapter/adapter.js:9115]: should we not add the same guard here again or better move to there?

Comment (foxriver76) [reply packages/adapter/src/lib/adapter/adapter.js:9115]: Yep after the async stuff
