### PR TITLE
do not crash if invalid version is in repo

### LINKED ISSUE #1392: adapter invalid version - crash iobroker update
grafik

grafik

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1392

### CODE REVIEW

File: packages/common/lib/common/tools.js [hunk 1]
```diff
@@ -159,6 +159,7 @@ function checkNonEditable(oldObject, newObject) {
 /**
  * @param {string} repoVersion
  * @param {string} installedVersion
+ * @throws
```
Comment (Apollon77) [inline packages/common/lib/common/tools.js:162]: throws what? :-)
