### PR TITLE
fix restoring backups which were created without config.system

### LINKED ISSUE #1889: Restore very old backup fails
https://forum.iobroker.net/topic/54067/wiederherstellung-error-abbruch/2

```
backitup.0
2022-04-09 00:43:59.660 error [ERROR] [iobroker] at BackupRestore._restoreAfterStop (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupBackup.js:686:52)
backitup.0
2022-04-09 00:43:59.658 error [ERROR] [iobroker] TypeError: Cannot read property 'hostname' of undefined
backitup.0
2022-04-09 00:43:59.655 error [ERROR] [iobroker] This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
```

### PR DESCRIPTION
**Pull request by foxriver76**
- closes #1889

### CODE REVIEW

File: packages/cli/src/lib/setup/setupBackup.ts [hunk 1]
```diff
@@ -679,18 +679,23 @@ export class BackupRestore {
...
+        if (!restore.objects) {
+            console.error('The backup does not contain any objects.');
+            return EXIT_CODES.CANNOT_RESTORE_BACKUP;
+        }
+
         // check that the same controller version is installed as it is contained in backup
         const exitCode = this._ensureCompatibility(
             controllerDir,
-            restore.config ? restore.config.system.hostname || hostname : hostname,
+            restore.config?.system ? restore.config.system.hostname || hostname : hostname,
```
Comment (AlCalzone) [inline packages/cli/src/lib/setup/setupBackup.ts:698]:
```suggestion
            restore.config?.system?.hostname || hostname,
```

Comment (AlCalzone) [reply packages/cli/src/lib/setup/setupBackup.ts:698]: not sure if `restore.config.system.hostname` can be empty. If not, I'd use `??` in place of `||`

**Review by AlCalzone — CHANGES_REQUESTED** [review]

File: packages/cli/src/lib/setup/setupBackup.ts (hunk 1 above)
Comment (foxriver76) [reply packages/cli/src/lib/setup/setupBackup.ts:698]: If empty string, the variable `hostname` should be applied, as it is done currently, so your suggestion makes sense to simplify it.
